# Generated by Django 3.1.4 on 2020-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201207_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
